import { createHash } from "crypto"
import { mkdir, writeFile } from "fs/promises"
import path from "path"
import { Operation } from "@/core/operation"
import type { OperationInfo } from "@/core/operation"
import { Plan } from "@/core/plan"
import { Observation } from "@/core/observation"
import { Evidence } from "@/core/evidence"
import type { Observation as Obs } from "@/core/observation/info"
import type { Node as PlanNode } from "@/core/plan/info"

const SEV_ORDER = ["critical", "high", "medium", "low", "info"] as const
type Sev = (typeof SEV_ORDER)[number]

function sha256(bytes: Buffer | string): string {
  return createHash("sha256").update(bytes).digest("hex")
}

function groupBySeverity(items: Obs[]): Record<Sev | "none", Obs[]> {
  const out: Record<string, Obs[]> = { critical: [], high: [], medium: [], low: [], info: [], none: [] }
  for (const o of items) out[o.severity ?? "none"].push(o)
  return out as Record<Sev | "none", Obs[]>
}

function renderReport(
  op: OperationInfo,
  plan: PlanNode[],
  observations: Obs[],
  evidence: Evidence.Entry[],
): string {
  const lines: string[] = []
  lines.push(`# ${op.label}`)
  lines.push("")
  lines.push(`- **Operation slug**: \`${op.slug}\``)
  lines.push(`- **Kind**: \`${op.kind}\``)
  lines.push(`- **Opsec**: \`${op.opsec}\``)
  lines.push(`- **Active**: \`${op.active}\``)
  lines.push(`- **Created**: \`${new Date(op.created_at).toISOString()}\``)
  lines.push(`- **Updated**: \`${new Date(op.updated_at).toISOString()}\``)
  if (op.target) lines.push(`- **Target**: \`${op.target}\``)
  lines.push("")

  lines.push("## Plan")
  if (plan.length === 0) lines.push("_empty_")
  else {
    const progress = Plan.progress(plan)
    lines.push(`_${progress.done}/${progress.total} done · ${progress.running} running · ${progress.blocked} blocked_`)
    lines.push("")
    const byParent = new Map<string | undefined, PlanNode[]>()
    for (const n of plan) {
      const p = n.parent_id
      if (!byParent.has(p)) byParent.set(p, [])
      byParent.get(p)!.push(n)
    }
    const render = (parent: string | undefined, depth: number) => {
      for (const n of byParent.get(parent) ?? []) {
        lines.push(`${"  ".repeat(depth)}- [${n.status}] ${n.title}`)
        render(n.id, depth + 1)
      }
    }
    render(undefined, 0)
  }
  lines.push("")

  lines.push("## Observations")
  const counts = Observation.severityCounts(observations)
  lines.push(
    `_${observations.length} total · ${counts.critical} critical · ${counts.high} high · ${counts.medium} medium · ${counts.low} low · ${counts.info} info · ${counts.none} unrated_`,
  )
  lines.push("")
  const grouped = groupBySeverity(observations)
  for (const sev of [...SEV_ORDER, "none"] as const) {
    const list = grouped[sev]
    if (list.length === 0) continue
    lines.push(`### ${sev === "none" ? "Unrated" : sev.charAt(0).toUpperCase() + sev.slice(1)}`)
    for (const o of list) {
      lines.push(`- **${o.title}** \`[${o.subtype}]\` · status=\`${o.status}\`${o.confidence != null ? ` · confidence=${o.confidence}` : ""}`)
      if (o.note) lines.push(`  - ${o.note.replace(/\n/g, " ")}`)
      if (o.tags.length > 0) lines.push(`  - tags: ${o.tags.map((t) => `\`${t}\``).join(", ")}`)
      if (o.evidence.length > 0) {
        lines.push(`  - evidence:`)
        for (const ev of o.evidence) lines.push(`    - \`${ev}\``)
      }
    }
    lines.push("")
  }

  lines.push("## Evidence Locker")
  if (evidence.length === 0) lines.push("_empty_")
  else {
    lines.push("| SHA-256 | Size | MIME | Label | Source |")
    lines.push("|---|---|---|---|---|")
    for (const e of evidence) {
      lines.push(
        `| \`${e.sha256}\` | ${e.size} | ${e.mime ?? "-"} | ${e.label ?? ""} | ${e.source ?? ""} |`,
      )
    }
  }
  lines.push("")
  lines.push("---")
  lines.push(`_Generated by numasec on ${new Date().toISOString()}_`)
  return lines.join("\n")
}

export interface Manifest {
  operation: string
  kind: string
  generated_at: number
  files: Array<{ path: string; sha256: string; size: number }>
  counts: { plan: number; observations: number; evidence: number }
}

export interface BuildResult {
  bundleDir: string
  manifest: Manifest
  reportPath: string
  manifestPath: string
}

export async function build(
  workspace: string,
  slug: string,
  options: { format?: "md" | "json" } = {},
): Promise<BuildResult> {
  const op = await Operation.get(workspace, slug)
  if (!op) throw new Error(`operation not found: ${slug}`)
  const [plan, observations, evidence] = await Promise.all([
    Plan.list(workspace, slug),
    Observation.list(workspace, slug),
    Evidence.list(workspace, slug),
  ])

  const stamp = new Date().toISOString().replace(/[:.]/g, "-")
  const bundleDir = path.join(
    workspace,
    ".numasec",
    "operation",
    slug,
    "deliverable",
    `bundle-${stamp}`,
  )
  await mkdir(bundleDir, { recursive: true })

  const files: Array<{ path: string; bytes: Buffer }> = []

  if (options.format !== "json") {
    const md = renderReport(op, plan, observations, evidence)
    files.push({ path: "report.md", bytes: Buffer.from(md, "utf8") })
  }

  const jsonPayload = JSON.stringify(
    { operation: op, plan, observations, evidence },
    null,
    2,
  )
  files.push({ path: "report.json", bytes: Buffer.from(jsonPayload, "utf8") })

  const manifest: Manifest = {
    operation: op.slug,
    kind: op.kind,
    generated_at: Date.now(),
    files: files.map((f) => ({ path: f.path, sha256: sha256(f.bytes), size: f.bytes.length })),
    counts: { plan: plan.length, observations: observations.length, evidence: evidence.length },
  }

  for (const f of files) {
    await writeFile(path.join(bundleDir, f.path), f.bytes)
  }
  const manifestBytes = Buffer.from(JSON.stringify(manifest, null, 2), "utf8")
  const manifestPath = path.join(bundleDir, "manifest.json")
  await writeFile(manifestPath, manifestBytes)

  const digest = sha256(manifestBytes)
  await writeFile(path.join(bundleDir, "manifest.sha256"), `${digest}  manifest.json\n`, "utf8")

  return {
    bundleDir,
    manifest,
    reportPath: path.join(bundleDir, "report.md"),
    manifestPath,
  }
}
