import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.NUMASEC_MODELS_URL || "https://models.dev"
const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")
const snapshotDeclarationPath = path.join(dir, "src/provider/models-snapshot.d.ts")
const bundledFallbackPath = path.join(dir, "test/tool/fixtures/models-api.json")

function enabled(value: string | undefined) {
  return value === "1" || value === "true" || value === "yes"
}

async function readExistingSnapshot() {
  const file = Bun.file(snapshotPath)
  if (!(await file.exists())) return

  const text = await file.text()
  const match = text.match(/export const snapshot = ([\s\S]*)\n?$/)
  const data = match?.[1]?.trim()
  return data && data !== "{}" ? data : undefined
}

async function readBundledFallback() {
  const file = Bun.file(bundledFallbackPath)
  if (!(await file.exists())) return
  return file.text()
}

async function readModelsData() {
  if (process.env.MODELS_DEV_API_JSON) {
    return Bun.file(process.env.MODELS_DEV_API_JSON).text()
  }

  if (enabled(process.env.NUMASEC_DISABLE_MODELS_FETCH)) {
    return (await readExistingSnapshot()) ?? (await readBundledFallback()) ?? "{}"
  }

  try {
    const result = await fetch(`${modelsUrl}/api.json`, {
      signal: AbortSignal.timeout(15_000),
    })
    if (!result.ok) throw new Error(`models.dev returned HTTP ${result.status}`)
    return await result.text()
  } catch (error) {
    console.warn(
      `Could not fetch ${modelsUrl}/api.json; generating a fallback model snapshot. Runtime model refresh remains available.`,
    )
    if (error instanceof Error) console.warn(error.message)
    return (await readExistingSnapshot()) ?? (await readBundledFallback()) ?? "{}"
  }
}

// Generate a bundled models.dev snapshot. This must not make local or CI
// releases depend on transient availability of the remote model catalogue.
const modelsData = await readModelsData()
await Bun.write(
  snapshotPath,
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  snapshotDeclarationPath,
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
